name: algo_visual
description: AlgoViualizer picks up on where most sorting visualizers left off. Now Visualizer the top 8 most famous sorting algorithms in tech in 6 different colors and 3 unique themes. 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_icon_button: ^0.3.0
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Segoe UI
      fonts:
        - asset: fonts/Segoe_UI.ttf
        - asset: fonts/Segoe_UI_Italic.ttf
        - asset: fonts/Segoe_UI_Bold.ttf
        - asset: fonts/Segoe_UI_Bold_Italic.ttf
